### PR TITLE
Update before_build.sh to solve version mismatch between chrome and its driver

### PR DESCRIPTION
**Pull request by gnoireaux**
Upgrading chrome to match driver which is more recent than expected. Cause for newness is still unknown, but no longer matters.

### CODE REVIEW

**Comment by gnoireaux** [comment]
Might be useful: how to run a Travis build locally:
```
docker run --name travis-debug -dit travisci/ci-garnet:packer-1512502276-986baf0 /sbin/init
docker exec -it travis-debug bash -l

su - travis
sudo service mongod start
git clone --depth=50 --branch=master https://github.com/locomotivecms/engine.git locomotivecms/engine
cd locomotivecms/engine
./bin/ci/before_build.sh
rvm use 2.5.0 --install --binary --fuzzy
export BUNDLE_GEMFILE=$PWD/Gemfile
bundle install --jobs=3 --retry=3 --deployment
bundle exec rake travis
```

Beware, your docker might grow by a bit more than 11GB!
```
~> docker images
REPOSITORY            TAG                         IMAGE ID            CREATED             SIZE
travisci/ci-garnet    packer-1512502276-986baf0   6cbda6a950d3        12 months ago       10.2GB
~> docker ps -as
CONTAINER ID        IMAGE                                          COMMAND             CREATED             STATUS              PORTS               NAMES               SIZE
87cdb58e87fc        travisci/ci-garnet:packer-1512502276-986baf0   "/sbin/init"        24 minutes ago      Up 24 minutes       22/tcp              travis-debug        988MB (virtual 11.2GB)
```

More info: https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image

**Comment by gnoireaux** [comment]
The error from version mismatch no longer happens since the `chromedriver-helper` gem no longer downloads a more recent version than the before build script.
```
Failure/Error: e = error
            
            Selenium::WebDriver::Error::SessionNotCreatedError:
              session not created: Chrome version must be between 70 and 73
                (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-101-generic x86_64)
```
But now, there are errors like these:
```
Failures:
  1) A site with a form content type it submits the form in HTML with valid inputs
     Failure/Error: fill_in 'Email', with: @account.email
     
     Capybara::ElementNotFound:
       Unable to find field "Email"
     
     [Screenshot]: spec/dummy/tmp/screenshots/failures_r_spec_example_groups_a_site_with_a_form_content_type_it_submits_the_form_in_html_with_valid_inputs_457.png
```

There is only the `jest` error when running in a local travis docker container. Only travis-ci.org breaks 👎

**Comment by did** [comment]
hey @gnoireaux, alright, build fixed! it didn't work for 2 reasons:
- the custom host defined in the travis.yml was not used by their platform (I changed the syntax)
- because we wanted to test with Rails eager loading on, we had some weird issues during the build. Fixed by changing the way we organize our javascript (Ruby was loading ruby code from the node_modules folder breaking everything in our app).
Again, thanks for your help!

**Comment by gnoireaux** [comment]
Great! Glad I could help!
And thanks for the feedback.

**Pull request closed without merging**
