### PR TITLE
Turkish

### PR DESCRIPTION
**Pull request by edgerunner**
Here is a Turkish translation. Hope everything is in the right place… Let me know if otherwise.

### CODE REVIEW

**Comment by did** [comment]
hi @edgerunner!

First of all, thank you so much for that! However, we switched over to Transifex to manage the translations. 
Would you mind using it to translate v3? Here is the link to start to translate: https://www.transifex.com/locomotive/locomotive-engine. 
Thanks again!

**Comment by edgerunner** [comment]
Sure, the next time I find some spare time

**Comment by edgerunner** [comment]
@did, I put a request in for Turkish at Transifex.

**Comment by did** [comment]
hi @edgerunner. Thank you!!! No rush! I just wanted to let you know that we changed our way to manage the back-office translations.

**Comment by edgerunner** [comment]
Logged in today and tried out transifex. Looks good. I'll do it as I get the time.

**Pull request closed without merging**
