### PR TITLE
Add Ukrainian locale

### PR DESCRIPTION
**Pull request by timsly**
I did a request in transifex, but didn't get any confirmation email(i realized that i used old email there) so decided to translate it directly.
It also contains fix for datepicker localization. Because it has issue with ukrainian locale.

### CODE REVIEW

**Comment by did** [comment]
hi @timsly, first, thank you for your hard work! 
However and I feel sorry for you but transifex is a requirement to manage translations, otherwise it becomes a mess. Let me know how I can help you on transifex.
Again, super sorry :-(

**Comment by timsly** [comment]
@did That's ok, i will just put all my translations to transifex. But i would still leave here fix for datepicker.
So can you please approve my request(for uk locale) in transifex?

**Comment by did** [comment]
@timsly What was the issue? https://github.com/timsly/engine/blob/uk-locale/vendor/assets/javascripts/locomotive/datepicker_i18n.js.erb#L19

**Comment by timsly** [comment]
@did in Ukrainian `Friday` is `П'ятниця`. As you see it contains quote. So without my fix datepicker_i18n.js will contain smth like
```javascript
$.datepicker.regional['uk'] = {
  dayNames: 'day1', 'day2', ...,  'П'ятниця
}
```
This code will raise error on assets precompilation.
To prevent it we need use `\'` instead of  `'`

**Comment by timsly** [comment]
@did I removed all `*uk.yml` files from the PR(i was able to upload them all to the transifex via api)
I left only fix for `datepicker_i18n.js`, because without it uk locale won't work.

**Comment by did** [comment]
thanks @timsly! That's perfect!

**Comment by timsly** [comment]
@did when are you going to release Ukrainian translation?

**Pull request merged**
